FROM pypy:3-5.8.0

# Application setup
COPY requirements-to-freeze.txt requirements-to-freeze.txt
CMD pip install -r requirements-to-freeze.txt

COPY . .

CMD pytest --junitxml=/data/test_report.xml \
           --cov-report xml:/data/coverage.xml

CMD pylint > pylint.log
